base_url = "/blog"
compile_sass = true
title = "Cesar's blog"
description = "Aquí escribo las cosas que quiero plasmar de manera más coherente que mis ideas, que no suelen ser muy claras."
# generate_feed = true

taxonomies = [
    # {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "César"
after_dark_menu = [
    {url = "$BASE_URL", name = "Inicio"},
    # {url = "$BASE_URL/categories", name = "Categorías"},
    {url = "$BASE_URL/tags", name = "Etiquetas"},
]
after_dark_title = "El blog de César / César's blog"
